In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

class Dense:
    def __init__(self, units, name, activation='sigmoid'):
        self.units = units
        self.name = name
        self.activation = activation
        self.weights = None
        self.bias = np.zeros(units)
        self.inputs = None
        self.output = np.zeros(units)
        self.activation = self.get_activation(activation)
    
    def sigmoid(self, z: np.array ) -> np.array:
        return 1 / (1 + np.exp(-z))
    
    def linear(self, z: np.array) -> np.array:
        return z
    
    def relu(self, z: np.array) -> np.array:
        return np.maximum(0, z)
    
    def softmax(self, z: np.array) -> np.array:
        return np.exp(z) / np.sum(np.exp(z))
    
    def get_activation(self, activation):
        if activation == 'sigmoid':
            return self.sigmoid
        elif activation == 'linear':
            return self.linear
        elif activation == 'relu':
            return self.relu
        elif activation == 'softmax':
            return self.softmax
    
    def __call__(self, inputs):
        _, feature_size = inputs.shape
        self.inputs = inputs
        self.weights = np.random.randn(feature_size, self.units)
        z =  np.matmul(self.inputs, self.weights) + self.bias
        g = self.activation(z)
        self.output = g
        return self.output
    
    def get_wights(self):
        return self.weights, self.bias
        
    def get_output(self):
        return self.output

class Sequential:
    def __init__(self, layers):
        self.layers = layers
        self.hashtable = {}
        for layer in layers:
            layer_name = layer.name
            self.hashtable[layer_name] = layer
    
    def fit(self, data):
        for layer in self.layers:
            data = layer(data)

    def get_layer(self, layer_name):
        if layer_name not in self.hashtable:
            raise Exception(f'Layer {layer_name} not found')
        return self.hashtable[layer_name]

In [2]:
model = Sequential([
    Dense(units=3, activation='relu', name='layer1'),
    Dense(units=1, activation='sigmoid', name='layer2')
])

model.fit(np.array([[1,2]]))

In [3]:
print(model.get_layer('layer1').get_wights())
print(model.get_layer('layer2').get_wights())

(array([[-0.86211224,  0.64946616,  1.09691676],
       [-0.36277704, -0.86748198, -0.30806097]]), array([0., 0., 0.]))
(array([[-1.68699141],
       [ 1.15007355],
       [ 1.41647134]]), array([0.]))


In [4]:
print(model.get_layer('layer1').get_output())
print(model.get_layer('layer2').get_output())

[[0.         0.         0.48079483]]
[[0.66396901]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=39a136b1-8191-420f-afab-bb238316f4d7' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>